name:                git-bisect
version:             0.3.0
#github:              raehik/ukc-co663-git-bisect
license:             MIT
author:              Ben Orchard / bo207 / @raehik
#maintainer:          "example@example.com"
copyright:           "2020 Ben Orchard (@raehik)"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/git-bisect#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- text >= 1.2
- aeson >= 1.4
- websockets >= 0.12
- bytestring >= 0.10
- either >= 5.0

library:
  source-dirs: src

executables:
  git-bisect-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-bisect

tests:
  git-bisect-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-bisect
